### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by terminator-ger** [terminator-ger/Conversations#1]
- [ ] options to mark incomming messages with green bubbles in every theme
- [ ] fix message text color
- [ ] add red bubbles for unsecure messages in new theme
- [ ] add amoled-black theme
